project_id = "tbuszxkevkpjcjapbrir"

[functions.suggest-foods]
verify_jwt = false

[functions.suggest-recipe]
verify_jwt = true

[functions.ai-meal-plan]
verify_jwt = true

[functions.test-ai-model]
verify_jwt = true

[functions.generate-blog-content]
verify_jwt = true

[functions.generate-social-content]
verify_jwt = true
