project_id = "tbuszxkevkpjcjapbrir"

[functions.calculate-food-similarity]
verify_jwt = true

[functions.suggest-foods]
verify_jwt = true

[functions.suggest-recipe]
verify_jwt = true

[functions.ai-meal-plan]
verify_jwt = true

[functions.test-ai-model]
verify_jwt = true

[functions.generate-blog-content]
verify_jwt = false

[functions.generate-social-content]
verify_jwt = false

[functions.test-blog-webhook]
verify_jwt = false

[functions.update-blog-image]
verify_jwt = false

[functions.parse-recipe]
verify_jwt = false
